spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mshop
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #jdbc:h2:tcp://localhost/~/mshop jdbc:mysql://skorea.duckdns.org/mshop
    #org.h2.Driver com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#      show_sql: true
        format_sql: true
        # fetch size는 쿼리 한번에 in절에 (?, ? ..) 총 몇개가 들어갈것인지. 100~1000 추천, 500~800추천
        default_batch_fetch_size: 1000
    # osiv 대규모 트래픽 발생시 false.
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace